config/routes.rb
Rails.application.routes.draw do
  resources :movies
  get 'static_pages/home'

  get 'static_pages/movies'

    root 'application#hello'
    get  '/registro',  to: 'users#new'
    post  '/users',  to: 'users#store'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    post  '/rent_a_movie',  to: 'movies#make_a_rent'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    mount_uploader :poster, PosterUploader
    validates :titulo, presence: true
    validates :descripcion, presence: true
    validates :productor, presence: true
    validates :genero, presence: true
    validates :precio, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, 
                                format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, 
                                uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper

    def hello
    render template: "aplication/hello"
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Por favor inicia sesión."
        redirect_to login_url
      end
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :logged_in_user
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    # movie = Movie.find(params[:id])
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def make_a_rent
    respond_to do |format|
        success = rand(0..1)
        format.json { head :no_content }
        format.js   { render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:titulo, :descripcion, :productor, :genero, :precio, :poster, :calificacion)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            log_in user
            redirect_to movies_path
        else
            flash[:danger] = 'Correo o contraseña incorrectos.'
            render 'new'
    end
    end

    def destroy
        log_out
        redirect_to root_url
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def movies
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def store
    @user = User.new(user_params) 
    if @user.save
        flash[:success] = "Bienvenido a Rails Videoclub!"
        log_in @user
        redirect_to movies_path
    else
        render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/aplication/hello.html.erb
<div class="center jumbotron">
  <h1>Bienvenido a nuestro VideoClub</h1>

  <h2>
    Para poder comenzar a rentar peliculas necesitas registrarte.
  </h2>

  <%= link_to "Registrarme", registro_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        <a href="http://www.andradedev.com/">Jorge Andrade</a>
    </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoClub | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Rails VideoClub</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><li><%= link_to "Peliculas",   movies_path %></li></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if !logged_in? %>
              <li><%= link_to "Iniciar sesión",   login_path %></li>
            <% else %>
              <li><%= link_to "Cerrar sesión",   logout_path, method: "delete"  %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_for @movie, html: { multipart: true } do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <%= f.label :titulo %>
      <%= f.text_field :titulo %>

      <%= f.label :descripcion %>
      <%= f.text_area :descripcion %>

      <%= f.label :productor %>
      <%= f.text_field :productor %>

      <%= f.label :poster %>
      <%= f.file_field :poster %>

      <%= f.label :genero %>
      <%= f.text_field :genero %>

      <%= f.label :precio %>
      <%= f.text_field :precio %>

      <%= f.label :calificacion %>
      <%= f.text_field :calificacion %>

    <%= f.submit "Guardar", class: "btn btn-primary" %>
<% end %>

  </div>
</div>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

app/views/movies/index.html.erb
<h1>Peliculas 
<% if logged_in? %>
<small><%= link_to 'Agregar pelicula', new_movie_path %></small>
<% end %>
</h1>

<div class="row">
  <% @movies.each do |movie| %>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <img src="<%= movie.poster_url %>" alt="<%= movie.titulo %>" class="img-responsive">
      <div class="caption">
        <h3><%= movie.titulo %></h3>
        <p>Genero: <%= movie.genero %></p>
        <p>Calificación: <%= movie.calificacion %></p>
        <p>Precio de renta: <%= movie.precio %></p>
        <p>
          <%= link_to 'Ver', movie, class: "btn btn-primary" %>
          <% if logged_in? %>
            <%= link_to 'Editar', edit_movie_path(movie), class: "btn btn-success" %>
            <%= link_to 'Eliminar', movie, method: :delete, class: "btn btn-danger", data: { confirm: '¿Seguro de eliminarla?' } %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/movies/make_a_rent.js.erb
$('.make_rent').bind('ajax:success', function() {
   if (Math.floor((Math.random() * 2) + 1) == 1) {
    alert('Se completó la renta');
    window.location.href ="/movies";
   }
   else{
    alert('No se le puede rentar porque tiene deudas');
   }
});

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<div class="row">
    <div class="col-md-3">
        <img src="<%= @movie.poster_url %>" alt="<%= @movie.titulo %>" class="img-responsive">
    </div>
    <div class="col-md-9">
        <h1><%= @movie.titulo %></h1>
        <p>Productor: <%= @movie.productor %></p>
        <p>Genero: <%= @movie.genero %></p>
        <p>Calificación: <%= @movie.calificacion %></p>
        <p>Precio de renta: <%= @movie.precio %></p>
        <p class="lead"><%= @movie.descripcion %></p>

        <% if logged_in? %>
        <a><%= link_to 'Rentar', rent_a_movie_path, method: :post, class: 'btn btn-primary btn-lg make_rent', remote: true %></a>
        <% end %>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Verifique sus datos.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/static_pages/movies.html.erb
<h1>StaticPages#movies</h1>
<p>Find me in app/views/static_pages/movies.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Registro</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Registrarme", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>